import React, { useEffect, useRef } from "react";
import * as yup from "yup";
import { useFormik } from "formik";
import { Delete2FAPayload, UseThunkActionCreator } from "../../../types";
import { BindHotKeys, Input, Button, Label } from "../../../components";
import { Modal, FormErrors } from "../../../modules/index";

const validationSchema = yup.object().shape({
  code: yup.string().required("This field is required."),
});

interface Props {
  submit: () => Promise<void>;
  cancel: () => void;
  delete2FA: (data: Delete2FAPayload) => UseThunkActionCreator<void>;
}
const Disable2FA: React.FC<Props> = ({ submit, cancel, delete2FA }) => {
  const inputRef = useRef<HTMLInputElement>(null);
  const {
    isValid,
    dirty,
    handleSubmit,
    handleChange,
    handleBlur,
    values,
    errors,
    touched,
    isSubmitting,
  } = useFormik({
    validationSchema,
    initialValues: {
      code: "",
      detail: "",
    },
    onSubmit: (formValues, { setErrors }) => {
      return delete2FA({ code: formValues.code }).then(
        () => {
          submit();
        },
        (err) => {

          setErrors(err);
        }
      );
    },
  });
  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus();
    }
  });
  return (
    <BindHotKeys callback={handleSubmit} rejectCallback={cancel}>
      <Modal title={<div className="theme-text-red">Disable 2FA</div>} onClose={cancel}>
        <form onSubmit={handleSubmit}>
          <Modal.Body>
            <p className="mb-6 text-xl font-bold">Are you sure?</p>
            <p className="mb-3">This will disable Two-factor authentication entirely.</p>
            <p className="mb-6">For security purposes, please enter the code generated by your authentication device.</p>
            <div className="form-field">
              <Label label="Authentication code">
                <div className="w-3/4">
                  <Input
                    ref={inputRef}
                    type="text"
                    name="code"
                    value={values.code}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    className="tracking-widest"
                    maxLength={6}
                    placeholder="XXXXXX"
                    error={touched.code && errors.code || ""}
                  />
                </div>
              </Label>
            </div>
            <FormErrors errors={errors} />
          </Modal.Body>
          <Modal.Actions>
            <div className="flex justify-end space-x-3">
              <Button
                type="button"
                name="cancel-btn"
                onClick={cancel}
              >
                Cancel
                  </Button>
              <Button
                disabled={!isValid || !dirty || isSubmitting}
                type="submit"
                name="submit-btn"
                loading={isSubmitting}
                variant={Button.variant.RED}
              >
                Disable 2FA
                  </Button>
            </div>
          </Modal.Actions>
        </form>
      </Modal>
    </BindHotKeys>
  );
};

export default Disable2FA;
