import React from "react";
import * as yup from "yup";
import { useFormik } from "formik";
import { createModal } from "promodal";
import { BindHotKeys, Input, Button, Label } from "../../../components";
import { Modal, FormErrors } from "../../../modules/index";

const validationSchema = yup.object().shape({
  code: yup.string().required("This field is required."),
});

interface Props {
  submit: (code: string) => Promise<void>;
  cancel: () => void;
}
const Enter2FACode: React.FC<Props> = ({ submit, cancel }) => {
  const {
    isValid,
    dirty,
    handleSubmit,
    handleChange,
    handleBlur,
    values,
    errors,
    touched,
    isSubmitting,
  } = useFormik({
    validationSchema,
    initialValues: {
      code: "",
      non_field_errors: "",
    },
    onSubmit: (formValues, { setErrors }) => {
      submit(formValues.code)
        .catch(
          (err: any) => {
            setErrors(err);
          }
        );
    },
  });
  return (
    <BindHotKeys callback={handleSubmit} rejectCallback={cancel}>
      <Modal
        title="2FA Confirmation"
        goBackCallback={cancel}
      >
        <div>
          <p className="mb-6 text-xl">Please confirm your action.</p>
          <p className="mb-6">For security purposes, please enter the code generated by your authentication device.</p>
          <form onSubmit={handleSubmit}>
            <div className="form-field">
              <Label label="Enter your verification code">
                <Input
                  type="text"
                  name="code"
                  value={values.code}
                  onChange={handleChange}
                  onBlur={handleBlur}
                  className="tracking-widest"
                  maxLength={6}
                  placeholder="XXXXXX"
                  error={touched.code && errors.code || ""}
                />
              </Label> 
            </div>
            <FormErrors errors={errors} />
            <div className="flex space-x-3 mt-10">
              <Button
                type="button"
                name="cancel-btn"
                onClick={cancel}
                block
              >
                Cancel
              </Button>
              <Button
                disabled={!isValid || !dirty || isSubmitting}
                type="submit"
                name="submit-btn"
                loading={isSubmitting}
                block
              >
                Confirm
              </Button>
            </div>
          </form>
        </div>
      </Modal>
    </BindHotKeys>
  );
};

export default createModal(Enter2FACode);
