export default {
  login: "/login",
  register: "/register",
  emailConfirm: "/accounts/activation/:userId/:token",
  resetPassword: "/accounts/password/*",
  profile: "/profile",
  home: "/",
  wallets: "/wallets",
  wallet: "/wallets/:id/*",
  newWallet: "/new-wallet",
  changeEmail: "/change-email/:token",
  components: "/components",
  keypair: "/keypair",
  security: "/security",
  acknowledgments: "/acknowledgments",
  security_pgp_key: "/security-pgp-key",
  terms_of_service: "/terms-of-service",
  privacy_policy: "/privacy-policy",
  cookie_policy: "/cookie-policy",
  faq: "/faq",
  not_found: "/404",
};
